### ISSUE TITLE
Port always rendered in displayed links

### ISSUE THREAD

**Issue by jisantuc** [azavea/franklin#168]
**Describe the bug**
Deployed instances probably don't need to advertise `franklin.foo.com:9090` -- but they do. There's some handling for ports 443 and 80 with https and http for schemes, but this is at odds with a deployment story behind an AWS ALB, where the individual services can be running on basically any port, and the ALB is listening to https traffic on 443, but the service is still running on whatever port.

**Expected behavior**
Links work in deployed Franklin services

**Comment by notthatbreezy** [comment]
There's a `--public-port` setting that can be set to prevent this. This allows for differentiating between the server port and what should be advertised to end users because the service is behind a reverse proxy.

**Comment by jisantuc** [comment]
Oh, I misunderstood the link between `--external-port` and `publicPort`. All set, nevermind!
