### ISSUE TITLE
Tests Left to Write

### ISSUE THREAD

**Issue by notthatbreezy** [azavea/franklin#17]
# Datamodel
- [x] `serde` spec to verify that we can serialize/deserialize the json we expect

# DAO
- ~StacItemDAO~
- ~`StacCollectionDao`~

# API
- [x] Collection Item Services
- [x] `CollectionsService`

For the API tests, make sure that they're [tagged](https://etorreborre.github.io/specs2/guide/SPECS2-4.8.3/org.specs2.guide.Selection.html) so that we can use use filter arguments to run specific tests for easier local testing

**Comment by jisantuc** [comment]
Actually I was wrong about how tagging works -- they don't need to be tagged for us to do selection.

We can do, e.g.,

```bash
$ bloop test application -o "*SearchServiceSpec" -- ex "not find items when excluded by time"
```

and specs2 will only run the example that includes the line "not find items when excluded by time"

I somehow managed not to see that at the top of the Selection docs :man_shrugging:
