### ISSUE TITLE
Importer is really uninformative when it fails

### ISSUE THREAD

**Issue by jisantuc** [azavea/franklin#319]
**Describe the bug**
When the importer doesn't work, it's really hard to find out why, largely because we don't log anything useful. One reason we don't log anything I think is that we don't know how to do log levels with bloop. We should figure that out and then at a minimum report json deserialization errors, when that goes wrong.

**Expected behavior**
Failures to import collections/items produce useful logging output, so that I, a user, have any idea what I need to fix

**Comment by rowanwins** [comment]
Also a pretty similar experience when `POST`-ing to the API, at the moment I'm just getting `Invalid value for: body`
