### ISSUE TITLE
Update catalog insertions through import commands

### ISSUE THREAD

**Issue by micpilon** [azavea/franklin#342]
A nice improvement would be to have the capacity to update an existing collection in Franklin. Let's say I have a collection that is filled with new data on a certain basis in my organization, and that I would like to add this new content to an already existing collection in Franklin through updates. Using the import command, the only possibility would be to wipe out the table and re-import. Importing over the existing collection throws:

```
 org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "collections_pkey"
  Detail: Key (id)=(<collection-name>) already exists.
```

**Comment by jisantuc** [comment]
This is now possible! Has been for a bit via the `import-items` command
