### ISSUE TITLE
Add Pagination Support to `collections/<id>/items`

### ISSUE THREAD

**Issue by notthatbreezy** [azavea/franklin#361]
### Improvement

Right now a request to `collections/<id>/items` returns _all_ of a collection's items. For collections with thousands of items this can quickly get out of hand. We should add pagination support to this endpoint so as to not overload the server.

### Notes + Context

Currently the pagination extension in the stac specification is not fully documented and relies a bit on OGC API Features - it [appears](http://docs.opengeospatial.org/DRAFTS/17-069r1.html) that it is possible to paginate this as well.

**Comment by jisantuc** [comment]
This is [already implemented](https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/api/services/CollectionItemsService.scala#L51-L90) unless I'm very confused. Closing for now so that people will notice that I'm confused and correct me.
