### ISSUE TITLE
Document server startup options

### ISSUE THREAD

**Issue by jisantuc** [azavea/franklin#363]
### Improvement

We have a few options for things you can turn on and off when the server starts. However, what they do isn't documented anywhere. [That's a drag!](https://gitter.im/franklin-stac/community?at=5f294baf47738110233ec22e)

### Notes + Context

This should probably take the form of distinct but mutually reinforcing improvements:

- the README shouldn't list endpoints anymore. Instead, it should refer to the docs site. Having endpoints listed makes the README seem more useful than it actually is, which is _bad_
- The docs site should fill in the command help using the actual command help in the application. We can do this with `decline` + `mdoc`, see below
- the docs site should include a rendering of the OpenAPI spec (I think we can do this with the OpenAPI interpretation from tapir and then interpolate it with mdoc)
- the docs site should have documentation on what each flag does beyond what `--help` shows

Example rendering of help in Scala:

```scala
scala> Commands.applicationCommand.showHelp
res4: String =
Usage:
     serve
     migrate
     import-catalog
     import-items

Your Friendly Neighborhood OGC API - Features and STAC Web Service

Options and flags:
    --help
        Display this help text.

Subcommands:
    serve
        Runs web service
    migrate
        Runs migrations against database
    import-catalog
        Import a STAC catalog
    import-items
        Import STAC items into an existing collection
```

**Comment by CloudNiner** [comment]
Assuming that the quay.io/azavea/franklin:latest image is up to date with `master`, the example `import` command is incorrect on the docs page as well: https://azavea.github.io/franklin/docs/introduction#importing-data

`import` should be `import-catalog`

**Comment by jisantuc** [comment]
Update 2020/12/09: [still a drag](https://azavea.slack.com/archives/CM766K2QJ/p1607551399064300)

**Comment by CloudNiner** [comment]
But I did find some options documented (not sure if they're all correct though...): https://azavea.github.io/franklin/docs/introduction#running-the-service, scroll down to the second code block in that section.

**Comment by jisantuc** [comment]
Oh, I forgot those existed, thanks! They're missing `--run-migrations` and we could probably use more docs than what `--help` says, but I think @digitaltopo added those a bit ago and I forgot about it
