### ISSUE TITLE
Configure postgres with POSTGRES_URL/--postgres-url instead of building from components

### ISSUE THREAD

**Issue by digitaltopo** [azavea/franklin#394]
### Improvement

I'd like to connect Franklin to a hosted Postgres database via [Google Cloud SQL](https://cloud.google.com/sql) from within a cloud deployed container. I should be able to connect via Unix sockets. Would there be interest in submitting a PR that allows this?

### Notes + Context

- [Google Cloud SQL Instructions for connecting via Unix Sockets for Java](https://cloud.google.com/sql/docs/postgres/connect-run#java)

In [franklin/database/Config.scala](https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/database/Config.scala), `hikari` is used to setup database connection options. We could conditionally add the following settings:

```scala
hikariConfig.addDataSourceProperty("socketFactory", "com.google.cloud.sql.postgres.SocketFactory");
hikariConfig.addDataSourceProperty("cloudSqlInstance", CLOUD_SQL_CONNECTION_NAME);
```

Or conditionally allow for setting the `jdbcUrl` in [franklin/commands/DatabaseConfig.scala#L17](https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/commands/DatabaseConfig.scala#L17) to look like: 
```scala
jdbc:postgresql:///<DB_NAME>?cloudSqlInstance=<CLOUD_SQL_CONNECTION_NAME>&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=<DB_USER>&password=<DB_PASS>
```

Thanks and looking forward to any guidance on this.

**Comment by jisantuc** [comment]
We think it would make sense take a `--postgres-url` parameter / `POSTGRES_URL` environment variable, and let the user fill in whatever additional parameters they need. Does that sound sensible to you?

**Comment by digitaltopo** [comment]
Definitely!

**Comment by digitaltopo** [comment]
Definitely! Are you thinking that the `--postgres-url` would just override the `$dbHost:$dbPort/$dbName` in [`jdbcUrl`](https://github.com/azavea/franklin/blob/master/application/src/main/scala/com/azavea/franklin/commands/DatabaseConfig.scala#L17) if used?

**Comment by jisantuc** [comment]
Hey @digitaltopo I'm going to close this in favor of a (mostly) duplicate that covers GCP / k8s / ssl needs -- #669. Free to follow there
