### ISSUE TITLE
Allow passing full SQL connection URL to enable SSL options

### ISSUE THREAD

**Issue by adrienDog** [azavea/franklin#669]
### Improvement

Currently it seems not possible to enable SSL when connecting to the PostgreSQL database.

One simple way to achieve this would be to allow passing the full connection URL which would override the individual parameters:
```
DB_CONNECTION_URL="postgres://%s:%s@%s:%d/%s?sslmode=%s&sslrootcert=%s&sslcert=%s&sslkey=%s"
```

### Notes + Context
We would use this in the context of Franklin running in a Kubernetes pod, connecting to a managed Cloud SQL instance via private IP. 

Currently the only way to avoid this is to use a proxy, which is okay on a pod as a side car. It is actually the [recommended way in GCP](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine).

Unfortunately it is sometimes not practical, for example when running migrations in `initContainers` for example. In which case only running the proxy on another pod would work but then we add an extra unnecessary network hop.

**Comment by jisantuc** [comment]
👋🏻 we've been in principle good with this change previously, but not specifically for SSL reasons. The change to accept a URL itself is not very difficult, but I've never set up postgres with SSL locally -- do you know what testing / verification would look like for checking the SSL side of things?

**Comment by adrienDog** [comment]
Ah so in principle we could use the `POSTGRES_URL/--postgres-url` env variable / cli flag to specify it?

for testing with SSL specifically locally it is a good question, I have never done it either. What I've done in the past was to check the connection against the remote directly

**Comment by jisantuc** [comment]
Correct.

Are you able to test with the instance you'd like to connect to? If so, I can get a small PR up that enables this option, publish a public Franklin container image to my dockerhub account, and send you the image reference for a test.

**Comment by adrienDog** [comment]
Yes that would be perfect thanks a lot!

Let me know what you need in terms of results / screenshots to document the test results

**Comment by adrienDog** [comment]
Hi @jisantuc , in the meantime we will be using Cloud-SQL-proxy deployed in our K8S cluster to be a facade for our Cloud-SQL instance.

It is not our preferred option because it adds complexity to the system (extra component) and (a little) latency.

We will be ready to test the `POSTGRES_URL/--postgres-url` as soon as you need us to :)

**Comment by jisantuc** [comment]
Hey, it's been a bit on this since we've been pretty busy with other STAC adventures, but it's still on my radar. Sorry about the delay

**Comment by jisantuc** [comment]
Ugh it turns out this has been [possible ALL ALONG](https://github.com/tpolecat/doobie/blob/main/modules/hikari/src/main/scala/doobie/hikari/Config.scala#L44). Update incoming since now I need it for debugging a different adventure
