### ISSUE TITLE
Document query extension

### ISSUE THREAD

**Issue by adrienDog** [azavea/franklin#758]
### Improvement

Hi, recently Ive been trying to document our API more and I could not find documentation which explains the `query` extension.

This link is a `404` now https://github.com/radiantearth/stac-api-spec/tree/master/extensions/query

I saw an open issue regarding `CQL` to replace the query extension.

In the meantime, is there a place to reference and document the (deprecated I guess) `query` extension?

Thank you very much for your help

### Notes
- https://github.com/azavea/franklin/issues/471

**Comment by jisantuc** [comment]
There is -- you can use the tag for the previous published version which is pretty much a permalink: https://github.com/radiantearth/stac-api-spec/tree/v1.0.0-beta.1/fragments/query

**Comment by adrienDog** [comment]
ah yes thank you very much!
