### ISSUE TITLE
Items that were once part of a mosaic cannot be deleted

### ISSUE THREAD

**Issue by McSurf84** [azavea/franklin#884]
**Describe the bug**
If you create a mosaic for a collection, you can´t delete the items of the collection anymore. Even if you delete the mosaic first you´re not able to delete any items that were included with this mosaic anymore. The log shows
`Error servicing request: DELETE /collections/{collection_id}/items/{item_id}} from org.postgresql.util.PSQLException: ERROR: update or delete on table "collection_items" violates foreign key constraint "item_asset_histograms_item_id_fkey" on table "item_asset_histograms" Detail: Key (id)=({item_id}) is still referenced from table "item_asset_histograms".`

**Expected behavior**
When I delete items in a collection which are not linked to a mosaic, they will be deleted completely from the database.

**Comment by jisantuc** [comment]
Hey @McSurf84, good catch -- I'll add this to the milestone for the first tagged release
